server:
  port: 8082

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Uncomment if using PostgreSQL
# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/userdb
#     username: postgres
#     password: suvam123
#   jpa:
#     show-sql: true
#     database: POSTGRESQL
#     hibernate:
#       ddl-auto: update
#     database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true